### PR TITLE
telink: tl321x: adopt usb driver

### PR DESCRIPTION
**Pull request by pulin1103**
- update usb driver.
- update usb irq number in telink_tl321x.dtsi

### CODE REVIEW

**Comment by andriy-bilynskyy** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/f92eab672aac25a16d2807178664ea42ab8380e7 | https://github.com/telink-semi/hal_telink/pull/99 | [telink-semi/hal_telink#99/files](https://github.com/telink-semi/hal_telink/pull/99/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Review by damien0x0023 — COMMENTED** [review]
Do some naming changes for usb driver.

**Comment by liucoldstar** [comment]
@pulin1103 
The hal_telink PR has been merged.  Please update the hal_telink revision to  
f3eb7a8bc1712e2f9308c58276c875de1c7bde52
Andy

**Comment by damien0x0023** [comment]
> @pulin1103 The hal_telink PR has been merged. Please update the hal_telink revision to f3eb7a8bc1712e2f9308c58276c875de1c7bde52 Andy

Updated hal_telink revision and force push.

**Review by andy-liu-telink — APPROVED** [review]
Approve

**Pull request merged**
