### PR TITLE
riscv: telink: save bin size in retention mode.

### PR DESCRIPTION
**Pull request by haiwentelink**
- change the link file for b9x and tlx in retention .

### CODE REVIEW

**Comment by s07641069** [comment]
@haiwentelink I will run Jenkins with this changes to verify if everything ok
Will inform here later about Jenkins tests results

**Comment by s07641069** [comment]
@haiwentelink 
Jenkins tests passed.
Will be good to create same PR into https://github.com/telink-semi/zephyr/tree/develop_new branch, to help @andriy-bilynskyy avoid missed changes for new Zephyr version.

**Review by s07641069 — APPROVED** [review]

**Comment by haiwentelink** [comment]
OK, I will create the same PR to develop_new , but need to test by andrii .I don't have the environment. @andriy-bilynskyy  after that , we you can help to review and test

**Comment by s07641069** [comment]
PR into https://github.com/telink-semi/zephyr/tree/develop_new branch https://github.com/telink-semi/zephyr/pull/395

**Pull request merged**
