### PR TITLE
driver: usb: telink_b91: Fix DT reg property for USB

### PR DESCRIPTION
**Pull request by bojczmac**

### CODE REVIEW

**Comment by s07641069** [comment]
Add signed-off-by entries to pass compliance checks.

**Comment by andriy-bilynskyy** [comment]
Please fix CI

**Comment by bojczmac** [comment]
> Please fix CI

CI failed due to not working configuration: https://github.com/telink-semi/zephyr/actions/runs/3380994190/jobs/5614399082

**Review by s07641069 — APPROVED** [review]

**Comment by bojczmac** [comment]
Tested on: `samples/subsys/usb/hid-mouse`
```
[31917.072204] usb 1-2.1: new full-speed USB device number 5 using xhci_hcd
[31917.189145] usb 1-2.1: New USB device found, idVendor=248a, idProduct=5320, bcdDevice= 1.00
[31917.189147] usb 1-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[31917.189148] usb 1-2.1: Product: USB DevSys
[31917.189149] usb 1-2.1: Manufacturer: Telink Semiconductor 
[31917.202159] usblp 1-2.1:1.0: usblp3: USB Bidirectional printer dev 5 if 0 alt 0 proto 2 vid 0x248A pid 0x5320
[31917.202178] usbcore: registered new interface driver usblp
```

**Pull request merged**
