### PR TITLE
telink: tl321x: update BLE lib, hal_telink and zephyr to v4.0.4.2

### PR DESCRIPTION
**Pull request by damien0x0023**
update 
- sys_init parameter list in telink_tlx/soc.c.
- hal_telink and BLE lib.
according to BLE release tag v4.0.4.2

### CODE REVIEW

**Comment by andriy-bilynskyy** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/a7ba6a116666f2150931d31179a1083487a5b6ab | https://github.com/telink-semi/hal_telink/commit/478b9c07ccd9c974bb8e57ca4ca79b84abbebc28 (telink_tl321x) | [telink-semi/hal_telink@a7ba6a11..478b9c07](https://github.com/telink-semi/hal_telink/compare/a7ba6a116666f2150931d31179a1083487a5b6ab..478b9c07ccd9c974bb8e57ca4ca79b84abbebc28) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Review by s07641069 — CHANGES_REQUESTED** [review]
HAL code needs to cleaned and merged
In this PR no comments, lets wait merge of HAL

**Review by s07641069 — APPROVED** [review]

**Comment by s07641069** [comment]
update HAL rev after merge of HAL and as well squash commits into one

**Comment by damien0x0023** [comment]
> update HAL rev after merge of HAL and as well squash commits into one

Done.

**Pull request merged**
