### PR TITLE
west.yml: Updated telink clock driver

### PR DESCRIPTION
**Pull request by mishadesh**
Updated Telink clock driver due to bug in PLL.

### CODE REVIEW

**Comment by andriy-bilynskyy** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/5f572fc567cee5bbce0d71462e1bdf32ef52ecb4 (develop) | https://github.com/telink-semi/hal_telink/pull/29 | [telink-semi/hal_telink#29/files](https://github.com/telink-semi/hal_telink/pull/29/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by andriy-bilynskyy** [comment]
Please update hal telink revision: 2da1bb65e7384e5df603222c9606dbf0af7d30a2
As I understand USB sysbsystem now is not working when cpu clocks are less that 48M.
In that case it's good to add checker in telink usb driver and rise error with note.

**Comment by andriy-bilynskyy** [comment]
_drivers/usb/device/usb_dc_b91.c_
```
#if defined CONFIG_USB_TELINK_B91 && DT_PROP(DT_PATH(cpus, cpu_0), clock_frequency) < 48000000u
#error USB on current paltform requires CPU clocks frequency atleast 48Mhz.
#endif
```

**Comment by mishadesh** [comment]
After clarification with Damien, the USB is not working if USB clock divider is less than 2, the PLL source is not PLL_PAD_DIV and HCLK is not 48MHz.
It is not related to the core clock itself, it is related to the configuration of dividers.
So the proposed check is not valid, I will take a look how to add checks for all these limitations.

**Pull request closed without merging**
