### PR TITLE
west.yml: update hal telink

### PR DESCRIPTION
**Pull request by damien0x0023**
revert controller state names to fix sleep implementation.

### CODE REVIEW

**Review by s07641069 — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/9e86abb71b179007fc9a1fa03e84dd354b77b560 | https://github.com/telink-semi/hal_telink/commit/ec586d963cde41293340fd4b0697cf726afaf6a4 (develop) | [telink-semi/hal_telink@9e86abb7..ec586d96](https://github.com/telink-semi/hal_telink/compare/9e86abb71b179007fc9a1fa03e84dd354b77b560..ec586d963cde41293340fd4b0697cf726afaf6a4) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by s07641069** [comment]
@damien0x0023 Could you fix Compliance Checks?

**Comment by andriy-bilynskyy** [comment]
Seems these changes are already in develop_new.
@damien0x0023 please check the latest state. If everything is fine we can close this PR.

**Comment by damien0x0023** [comment]
> Seems these changes are already in develop_new. @damien0x0023 please check the latest state. If everything is fine we can close this PR.

Yes, TLX has been merged into develop_new and the hal_telink has also been updated.
This PR can be closed.

**Pull request closed without merging**
