### PR TITLE
drivers: ieee802154: telink: Optimize RF initialization process

### PR DESCRIPTION
**Pull request by pulin1103**
http://192.168.48.49:8080/browse/ZEPHYR-516
This modification is only for B9x without PM.

### CODE REVIEW

**Comment by andriy-bilynskyy** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/1c110b892f438ed491d480ea8fd0f4eb8f5ecfe1 (develop) | https://github.com/telink-semi/hal_telink/pull/82 | [telink-semi/hal_telink#82/files](https://github.com/telink-semi/hal_telink/pull/82/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by andriy-bilynskyy** [comment]
If PM is switched on code works exactly as it was (Just redundant radio init during driver starts or switching off BLE).
If PM is disabled we do not reinit radio. Inited just once at start.
So no any profit from PM perspective of view. Just SED device transmit little bit faster.
We had no issues with performance here.
But what is the profit of these changes? It seems just additional code complication.

**Comment by pulin1103** [comment]
The rf_baseband_reset in @damien0x0023‘s PR (https://github.com/telink-semi/hal_telink/pull/81) includes RF power down, which is currently the most effective way to switch modes and reset the RF module in B95.
So, for B95, there is a power-on operation for the RF module in rf_mode_int, frequent power cycling may affect the RF hardware circuit.
Although there is no similar operation in B91/B92, I think this initialization process can also be applied to B91/B92.
This PR can avoid the above-mentioned issues for non-PM devices, but there is currently no optimal solution for PM devices.

**Comment by andriy-bilynskyy** [comment]
[reduce_reinit.txt](https://github.com/telink-semi/zephyr/files/14944060/reduce_reinit.txt)
Ok in that case it's better to apply attached patch.
It's doing exactly what you say and provides minor changes.

**Comment by pulin1103** [comment]
Modify the PR according to your patch, and we should merge the hal_telink PR#81 at the same time; otherwise, Matter devices will be affected.

**Review by andriy-bilynskyy — APPROVED** [review]

**Pull request merged**
