### PR TITLE
drivers: ieee802154: b9x/tlx: Update cca features and function.

### PR DESCRIPTION
**Pull request by pulin1103**
- Update the CCA threshold.
- Improve the CCA calculation method.

### CODE REVIEW

**Comment by liucoldstar** [comment]
@s07641069 

The code changes are necessary for the low-power implementation. 
Could we run Jenkins testing for the proposed code changes before we approve this PR?

**Comment by s07641069** [comment]
> @s07641069
> 
> The code changes are necessary for the low-power implementation. Could we run Jenkins testing for the proposed code changes before we approve this PR?

Jenkins pipeline started with latest Matter master and Zephyr HASH 1eece674f93f8348a7a6d31ac3fa14e75d3ecd49
Later will inform about results.

**Comment by s07641069** [comment]
@liucoldstar 
Jenkins tests passed.
Will be good to create same PR into https://github.com/telink-semi/zephyr/tree/develop_new branch, to help @andriy-bilynskyy avoid missed changes for new Zephyr version.

**Review by s07641069 — APPROVED** [review]

**Comment by s07641069** [comment]
PR into https://github.com/telink-semi/zephyr/tree/develop_new branch https://github.com/telink-semi/zephyr/pull/395

**Review by damien0x0023 — APPROVED** [review]

**Pull request merged**
